# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import py_gitea_opensuse_org
from py_gitea_opensuse_org.models.general_repo_settings import GeneralRepoSettings  # noqa: E501
from py_gitea_opensuse_org.rest import ApiException

class TestGeneralRepoSettings(unittest.TestCase):
    """GeneralRepoSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test GeneralRepoSettings
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GeneralRepoSettings`
        """
        model = py_gitea_opensuse_org.models.general_repo_settings.GeneralRepoSettings()  # noqa: E501
        if include_optional :
            return GeneralRepoSettings(
                http_git_disabled = True, 
                lfs_disabled = True, 
                migrations_disabled = True, 
                mirrors_disabled = True, 
                stars_disabled = True, 
                time_tracking_disabled = True
            )
        else :
            return GeneralRepoSettings(
        )
        """

    def testGeneralRepoSettings(self):
        """Test GeneralRepoSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
