# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import py_gitea_opensuse_org
from py_gitea_opensuse_org.models.create_o_auth2_application_options import CreateOAuth2ApplicationOptions  # noqa: E501
from py_gitea_opensuse_org.rest import ApiException

class TestCreateOAuth2ApplicationOptions(unittest.TestCase):
    """CreateOAuth2ApplicationOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test CreateOAuth2ApplicationOptions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateOAuth2ApplicationOptions`
        """
        model = py_gitea_opensuse_org.models.create_o_auth2_application_options.CreateOAuth2ApplicationOptions()  # noqa: E501
        if include_optional :
            return CreateOAuth2ApplicationOptions(
                confidential_client = True, 
                name = '', 
                redirect_uris = [
                    ''
                    ]
            )
        else :
            return CreateOAuth2ApplicationOptions(
        )
        """

    def testCreateOAuth2ApplicationOptions(self):
        """Test CreateOAuth2ApplicationOptions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
