# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import py_gitea_opensuse_org
from py_gitea_opensuse_org.models.node_info_software import NodeInfoSoftware  # noqa: E501
from py_gitea_opensuse_org.rest import ApiException

class TestNodeInfoSoftware(unittest.TestCase):
    """NodeInfoSoftware unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test NodeInfoSoftware
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NodeInfoSoftware`
        """
        model = py_gitea_opensuse_org.models.node_info_software.NodeInfoSoftware()  # noqa: E501
        if include_optional :
            return NodeInfoSoftware(
                homepage = '', 
                name = '', 
                repository = '', 
                version = ''
            )
        else :
            return NodeInfoSoftware(
        )
        """

    def testNodeInfoSoftware(self):
        """Test NodeInfoSoftware"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
