# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import py_gitea_opensuse_org
from py_gitea_opensuse_org.models.watch_info import WatchInfo  # noqa: E501
from py_gitea_opensuse_org.rest import ApiException

class TestWatchInfo(unittest.TestCase):
    """WatchInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test WatchInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WatchInfo`
        """
        model = py_gitea_opensuse_org.models.watch_info.WatchInfo()  # noqa: E501
        if include_optional :
            return WatchInfo(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                ignored = True, 
                reason = None, 
                repository_url = '', 
                subscribed = True, 
                url = ''
            )
        else :
            return WatchInfo(
        )
        """

    def testWatchInfo(self):
        """Test WatchInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
