# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.26.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from py_gitea_opensuse_org.models.run_details import RunDetails

class TestRunDetails(unittest.TestCase):
    """RunDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RunDetails:
        """Test RunDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RunDetails`
        """
        model = RunDetails()
        if include_optional:
            return RunDetails(
                html_url = '',
                run_url = '',
                workflow_run_id = 56
            )
        else:
            return RunDetails(
        )
        """

    def testRunDetails(self):
        """Test RunDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
