# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictInt, StrictStr, conlist

class AccessToken(BaseModel):
    """
    AccessToken
    """
    id: Optional[StrictInt] = None
    name: Optional[StrictStr] = None
    scopes: Optional[conlist(StrictStr)] = None
    sha1: Optional[StrictStr] = None
    token_last_eight: Optional[StrictStr] = None
    __properties = ["id", "name", "scopes", "sha1", "token_last_eight"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccessToken:
        """Create an instance of AccessToken from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccessToken:
        """Create an instance of AccessToken from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccessToken.parse_obj(obj)

        _obj = AccessToken.parse_obj({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "scopes": obj.get("scopes"),
            "sha1": obj.get("sha1"),
            "token_last_eight": obj.get("token_last_eight")
        })
        return _obj

