# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.25.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ChangedFile(BaseModel):
    """
    ChangedFile store information about files affected by the pull request
    """ # noqa: E501
    additions: Optional[StrictInt] = Field(default=None, description="The number of lines added to the file")
    changes: Optional[StrictInt] = Field(default=None, description="The total number of changes to the file")
    contents_url: Optional[StrictStr] = Field(default=None, description="The API URL to get the file contents")
    deletions: Optional[StrictInt] = Field(default=None, description="The number of lines deleted from the file")
    filename: Optional[StrictStr] = Field(default=None, description="The name of the changed file")
    html_url: Optional[StrictStr] = Field(default=None, description="The HTML URL to view the file changes")
    previous_filename: Optional[StrictStr] = Field(default=None, description="The previous filename if the file was renamed")
    raw_url: Optional[StrictStr] = Field(default=None, description="The raw URL to download the file")
    status: Optional[StrictStr] = Field(default=None, description="The status of the file change (added, modified, deleted, etc.)")
    __properties: ClassVar[List[str]] = ["additions", "changes", "contents_url", "deletions", "filename", "html_url", "previous_filename", "raw_url", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChangedFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChangedFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "additions": obj.get("additions"),
            "changes": obj.get("changes"),
            "contents_url": obj.get("contents_url"),
            "deletions": obj.get("deletions"),
            "filename": obj.get("filename"),
            "html_url": obj.get("html_url"),
            "previous_filename": obj.get("previous_filename"),
            "raw_url": obj.get("raw_url"),
            "status": obj.get("status")
        })
        return _obj


