# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.25.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from py_gitea_opensuse_org.models.contents_response import ContentsResponse
from typing import Optional, Set
from typing_extensions import Self

class ContentsExtResponse(BaseModel):
    """
    ContentsExtResponse
    """ # noqa: E501
    dir_contents: Optional[List[ContentsResponse]] = Field(default=None, description="DirContents contains directory listing when the path represents a directory")
    file_contents: Optional[ContentsResponse] = None
    __properties: ClassVar[List[str]] = ["dir_contents", "file_contents"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContentsExtResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in dir_contents (list)
        _items = []
        if self.dir_contents:
            for _item_dir_contents in self.dir_contents:
                if _item_dir_contents:
                    _items.append(_item_dir_contents.to_dict())
            _dict['dir_contents'] = _items
        # override the default output from pydantic by calling `to_dict()` of file_contents
        if self.file_contents:
            _dict['file_contents'] = self.file_contents.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContentsExtResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "dir_contents": [ContentsResponse.from_dict(_item) for _item in obj["dir_contents"]] if obj.get("dir_contents") is not None else None,
            "file_contents": ContentsResponse.from_dict(obj["file_contents"]) if obj.get("file_contents") is not None else None
        })
        return _obj


