# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    The version of the OpenAPI document: 1.19.3
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr, conlist

class EditHookOption(BaseModel):
    """
    EditHookOption options when modify one hook
    """
    active: Optional[StrictBool] = None
    authorization_header: Optional[StrictStr] = None
    branch_filter: Optional[StrictStr] = None
    config: Optional[Dict[str, StrictStr]] = None
    events: Optional[conlist(StrictStr)] = None
    __properties = ["active", "authorization_header", "branch_filter", "config", "events"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> EditHookOption:
        """Create an instance of EditHookOption from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EditHookOption:
        """Create an instance of EditHookOption from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EditHookOption.parse_obj(obj)

        _obj = EditHookOption.parse_obj({
            "active": obj.get("active"),
            "authorization_header": obj.get("authorization_header"),
            "branch_filter": obj.get("branch_filter"),
            "config": obj.get("config"),
            "events": obj.get("events")
        })
        return _obj

