# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.25.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GeneralRepoSettings(BaseModel):
    """
    GeneralRepoSettings contains global repository settings exposed by API
    """ # noqa: E501
    http_git_disabled: Optional[StrictBool] = Field(default=None, description="HTTPGitDisabled indicates if HTTP Git operations are disabled")
    lfs_disabled: Optional[StrictBool] = Field(default=None, description="LFSDisabled indicates if Git LFS support is disabled")
    migrations_disabled: Optional[StrictBool] = Field(default=None, description="MigrationsDisabled indicates if repository migrations are disabled")
    mirrors_disabled: Optional[StrictBool] = Field(default=None, description="MirrorsDisabled indicates if repository mirroring is disabled")
    stars_disabled: Optional[StrictBool] = Field(default=None, description="StarsDisabled indicates if repository starring is disabled")
    time_tracking_disabled: Optional[StrictBool] = Field(default=None, description="TimeTrackingDisabled indicates if time tracking is disabled")
    __properties: ClassVar[List[str]] = ["http_git_disabled", "lfs_disabled", "migrations_disabled", "mirrors_disabled", "stars_disabled", "time_tracking_disabled"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GeneralRepoSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GeneralRepoSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "http_git_disabled": obj.get("http_git_disabled"),
            "lfs_disabled": obj.get("lfs_disabled"),
            "migrations_disabled": obj.get("migrations_disabled"),
            "mirrors_disabled": obj.get("mirrors_disabled"),
            "stars_disabled": obj.get("stars_disabled"),
            "time_tracking_disabled": obj.get("time_tracking_disabled")
        })
        return _obj


