# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.25.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TagProtection(BaseModel):
    """
    TagProtection represents a tag protection
    """ # noqa: E501
    created_at: Optional[datetime] = None
    id: Optional[StrictInt] = Field(default=None, description="The unique identifier of the tag protection")
    name_pattern: Optional[StrictStr] = Field(default=None, description="The pattern to match tag names for protection")
    updated_at: Optional[datetime] = None
    whitelist_teams: Optional[List[StrictStr]] = Field(default=None, description="List of team names allowed to create/delete protected tags")
    whitelist_usernames: Optional[List[StrictStr]] = Field(default=None, description="List of usernames allowed to create/delete protected tags")
    __properties: ClassVar[List[str]] = ["created_at", "id", "name_pattern", "updated_at", "whitelist_teams", "whitelist_usernames"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TagProtection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TagProtection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "id": obj.get("id"),
            "name_pattern": obj.get("name_pattern"),
            "updated_at": obj.get("updated_at"),
            "whitelist_teams": obj.get("whitelist_teams"),
            "whitelist_usernames": obj.get("whitelist_usernames")
        })
        return _obj


