# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.

    The version of the OpenAPI document: 1.26.4
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from py_gitea_opensuse_org.models.commit_date_options import CommitDateOptions
from py_gitea_opensuse_org.models.identity import Identity
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class UpdateFileOptions(BaseModel):
    """
    UpdateFileOptions options for updating or creating a file Note: `author` and `committer` are optional (if only one is given, it will be used for the other, otherwise the authenticated user will be used)
    """ # noqa: E501
    author: Optional[Identity] = None
    branch: Optional[StrictStr] = Field(default=None, description="branch (optional) is the base branch for the changes. If not supplied, the default branch is used")
    committer: Optional[Identity] = None
    content: StrictStr = Field(description="content must be base64 encoded")
    dates: Optional[CommitDateOptions] = None
    force_push: Optional[StrictBool] = Field(default=None, description="force_push (optional) will do a force-push if the new branch already exists")
    from_path: Optional[StrictStr] = Field(default=None, description="from_path (optional) is the path of the original file which will be moved/renamed to the path in the URL")
    message: Optional[StrictStr] = Field(default=None, description="message (optional) is the commit message of the changes. If not supplied, a default message will be used")
    new_branch: Optional[StrictStr] = Field(default=None, description="new_branch (optional) will make a new branch from base branch for the changes. If not supplied, the changes will be committed to the base branch")
    sha: Optional[StrictStr] = Field(default=None, description="the blob ID (SHA) for the file that already exists to update, or leave it empty to create a new file")
    signoff: Optional[StrictBool] = Field(default=None, description="Add a Signed-off-by trailer by the committer at the end of the commit log message.")
    __properties: ClassVar[List[str]] = ["author", "branch", "committer", "content", "dates", "force_push", "from_path", "message", "new_branch", "sha", "signoff"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UpdateFileOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of committer
        if self.committer:
            _dict['committer'] = self.committer.to_dict()
        # override the default output from pydantic by calling `to_dict()` of dates
        if self.dates:
            _dict['dates'] = self.dates.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UpdateFileOptions from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "author": Identity.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "branch": obj.get("branch"),
            "committer": Identity.from_dict(obj["committer"]) if obj.get("committer") is not None else None,
            "content": obj.get("content"),
            "dates": CommitDateOptions.from_dict(obj["dates"]) if obj.get("dates") is not None else None,
            "force_push": obj.get("force_push"),
            "from_path": obj.get("from_path"),
            "message": obj.get("message"),
            "new_branch": obj.get("new_branch"),
            "sha": obj.get("sha"),
            "signoff": obj.get("signoff")
        })
        return _obj


